{

//Reset ROOT and connect tree file
   TFile* f = new TFile("Data_7TeV.root");
   TTree* passedEvents = (TTree*)f->Get("AnaAfterHlt/passedEvents");

//Declaration of leaves types
   ULong64_t       Run;
   ULong64_t       Event;
   ULong64_t       LumiSect;
   TString         EventType;
   Double_t        mass4l;
   Double_t        ZZMass;
   Double_t        mass4lNoFSR;
   Double_t        mass4mu;
   Double_t        mass4e;
   Double_t        mass2e2mu;
   Double_t        minMass3l;
   Double_t        M3l_softestLep;
   Double_t        Z4l_maxP;
   Double_t        minDeltaR;
   Double_t        Z4l_thetaPhoton;
   Double_t        Z4l_thetaPhoton_deg;
   Double_t        Z4l_thetaPhotonZ;
   Double_t        Z4l_thetaPhotonZ_deg;
   Double_t        Z4l_theta12;
   Double_t        Z4l_theta13;
   Double_t        Z4l_theta14;
   Double_t        Z4l_theta12_deg;
   Double_t        Z4l_theta13_deg;
   Double_t        Z4l_theta14_deg;
   Double_t        Z4l_minMass2l;
   Double_t        Z4l_maxMass2l;
   Double_t        thetaZ2;
   Double_t        etaZ2;
   Bool_t          passedFullSelection;
   Bool_t          passedZ4lSelection;
   Bool_t          passedQCDcut;
   Int_t           finalState;
   Int_t           mixedFinalState;
   Double_t        scaleWeight;
   Double_t        eventWeight;
   Double_t        MC_weight;
   Double_t        pT4l;
   Double_t        massZ1;
   Double_t        massZ2;
   Double_t        Z1Mass;
   Double_t        Z2Mass;
   Double_t        eta4l;
   Double_t        phi4l;
   Int_t           idL1;
   Int_t           idL2;
   Int_t           idL3;
   Int_t           idL4;
   Int_t           missingHitsL1;
   Int_t           missingHitsL2;
   Int_t           missingHitsL3;
   Int_t           missingHitsL4;
   Bool_t          ecalSeedL1;
   Bool_t          ecalSeedL2;
   Bool_t          ecalSeedL3;
   Bool_t          ecalSeedL4;
   Double_t        EL1;
   Double_t        EL2;
   Double_t        EL3;
   Double_t        EL4;
   Double_t        EL1FSR;
   Double_t        EL2FSR;
   Double_t        EL3FSR;
   Double_t        EL4FSR;
   Double_t        mvaL1;
   Double_t        mvaL2;
   Double_t        mvaL3;
   Double_t        mvaL4;
   Double_t        SipL1;
   Double_t        SipL2;
   Double_t        SipL3;
   Double_t        SipL4;
   Double_t        IPL1;
   Double_t        IPL2;
   Double_t        IPL3;
   Double_t        IPL4;
   Double_t        dIPL1;
   Double_t        dIPL2;
   Double_t        dIPL3;
   Double_t        dIPL4;
   Double_t        EZ1;
   Double_t        EZ2;
   Double_t        pTL1;
   Double_t        pTL2;
   Double_t        pTL3;
   Double_t        pTL4;
   Double_t        pXL1;
   Double_t        pXL2;
   Double_t        pXL3;
   Double_t        pXL4;
   Double_t        pYL1;
   Double_t        pYL2;
   Double_t        pYL3;
   Double_t        pYL4;
   Double_t        pZL1;
   Double_t        pZL2;
   Double_t        pZL3;
   Double_t        pZL4;
   Double_t        pTL1FSR;
   Double_t        pTL2FSR;
   Double_t        pTL3FSR;
   Double_t        pTL4FSR;
   Double_t        pXL1FSR;
   Double_t        pXL2FSR;
   Double_t        pXL3FSR;
   Double_t        pXL4FSR;
   Double_t        pYL1FSR;
   Double_t        pYL2FSR;
   Double_t        pYL3FSR;
   Double_t        pYL4FSR;
   Double_t        pZL1FSR;
   Double_t        pZL2FSR;
   Double_t        pZL3FSR;
   Double_t        pZL4FSR;
   Double_t        pTZ1;
   Double_t        pTZ2;
   Double_t        pXZ1;
   Double_t        pXZ2;
   Double_t        pYZ1;
   Double_t        pYZ2;
   Double_t        pZZ1;
   Double_t        pZZ2;
   Int_t           chargeL1;
   Int_t           chargeL2;
   Int_t           chargeL3;
   Int_t           chargeL4;
   Double_t        etaL1;
   Double_t        etaL2;
   Double_t        etaL3;
   Double_t        etaL4;
   Double_t        phiL1;
   Double_t        phiL2;
   Double_t        phiL3;
   Double_t        phiL4;
   Double_t        isoTrackL1;
   Double_t        isoTrackL2;
   Double_t        isoTrackL3;
   Double_t        isoTrackL4;
   Double_t        isoEcalL1;
   Double_t        isoEcalL2;
   Double_t        isoEcalL3;
   Double_t        isoEcalL4;
   Double_t        isoHcalL1;
   Double_t        isoHcalL2;
   Double_t        isoHcalL3;
   Double_t        isoHcalL4;
   Double_t        isoNHL1;
   Double_t        isoNHL2;
   Double_t        isoNHL3;
   Double_t        isoNHL4;
   Double_t        isoCHL1;
   Double_t        isoCHL2;
   Double_t        isoCHL3;
   Double_t        isoCHL4;
   Double_t        isoPhotL1;
   Double_t        isoPhotL2;
   Double_t        isoPhotL3;
   Double_t        isoPhotL4;
   Double_t        RelIsoL1;
   Double_t        RelIsoL2;
   Double_t        RelIsoL3;
   Double_t        RelIsoL4;
   Double_t        RelIsoUCL1;
   Double_t        RelIsoUCL2;
   Double_t        RelIsoUCL3;
   Double_t        RelIsoUCL4;
   Double_t        muRho;
   Double_t        elRho;
   Double_t        worstIso;
   Double_t        worstSIP;
   Float_t         helcosthetaZ1;
   Float_t         helcosthetaZ2;
   Float_t         helphi;
   Float_t         costhetastar;
   Float_t         phistarZ1;
   Int_t           nJets;
   Int_t           nVtx;
   Int_t           nPhotons;
   Double_t        metVal;
   Int_t           extraLep_id[10];
   Double_t        extraLep_pT[10];
   Double_t        extraLep_pX[10];
   Double_t        extraLep_pY[10];
   Double_t        extraLep_pZ[10];
   Double_t        extraLep_e[10];
   Double_t        extraLep_iso[10];
   Double_t        extraLep_chIso[10];
   Double_t        extraLep_nhIso[10];
   Double_t        extraLep_phIso[10];
   Double_t        extraLep_eta[10];
   Double_t        extraLep_phi[10];
   Double_t        extraLep_sip[10];
   Double_t        massErrorUF;
   Double_t        massErrorUFCorr;
   Double_t        massErrorUCSD;
   Double_t        massErrorUCSDCorr;
   Bool_t          FSR_Z1;
   Bool_t          FSR_Z2;
   Double_t        FSRPhot1_Pt;
   Double_t        FSRPhot2_Pt;
   Double_t        FSRPhot1_eta;
   Double_t        FSRPhot2_eta;
   Double_t        FSRPhot1_phi;
   Double_t        FSRPhot2_phi;
   Double_t        FSRPhot1_Px;
   Double_t        FSRPhot2_Px;
   Double_t        FSRPhot1_Py;
   Double_t        FSRPhot2_Py;
   Double_t        FSRPhot1_Pz;
   Double_t        FSRPhot2_Pz;
   Double_t        FSRPhot1_E;
   Double_t        FSRPhot2_E;
   Double_t        pdfSigM4l;
   Double_t        pdfSigM4l_noFSR;
   Double_t        pdfBkgM4l;
   Double_t        pdfBkgM4l_noFSR;
   Double_t        pdfSigM4l_ScaleUp;
   Double_t        pdfSigM4l_ScaleUp_noFSR;
   Double_t        pdfBkgM4l_ScaleUp;
   Double_t        pdfBkgM4l_ScaleUp_noFSR;
   Double_t        pdfSigM4l_ScaleDown;
   Double_t        pdfSigM4l_ScaleDown_noFSR;
   Double_t        pdfBkgM4l_ScaleDown;
   Double_t        pdfBkgM4l_ScaleDown_noFSR;
   Double_t        pdfSigM4l_ResUp;
   Double_t        pdfSigM4l_ResUp_noFSR;
   Double_t        pdfBkgM4l_ResUp;
   Double_t        pdfBkgM4l_ResUp_noFSR;
   Double_t        pdfSigM4l_ResDown;
   Double_t        pdfSigM4l_ResDown_noFSR;
   Double_t        pdfBkgM4l_ResDown;
   Double_t        pdfBkgM4l_ResDown_noFSR;
   Double_t        melaLD;
   Double_t        mela_Sig;
   Double_t        mela_Bkg;
   Float_t         pseudoMelaLD;
   Float_t         pseudoMela_SM;
   Float_t         pseudoMela_PS;
   Float_t         spin1EvMelaLD;
   Float_t         spin1EvMela_SM;
   Float_t         spin1EvMela_S1E;
   Float_t         spin1OddMelaLD;
   Float_t         spin1OddMela_SM;
   Float_t         spin1OddMela_S1O;
   Float_t         spin2MelaLD;
   Float_t         spin2Mela_SM;
   Float_t         spin2Mela_S2;
   Double_t        MEKD_wPDF;
   Double_t        MEKD_ME_H_wPDF;
   Double_t        MEKD_ME_ZZ_wPDF;
   Double_t        MEKD_noPDF;
   Double_t        MEKD_ME_H_noPDF;
   Double_t        MEKD_ME_ZZ_noPDF;
   Double_t        MEKD_wPDF_noFSR;
   Double_t        MEKD_ME_H_wPDF_noFSR;
   Double_t        MEKD_ME_ZZ_wPDF_noFSR;
   Double_t        MEKD_noPDF_noFSR;
   Double_t        MEKD_ME_H_noPDF_noFSR;
   Double_t        MEKD_ME_ZZ_noPDF_noFSR;
   Double_t        interferenceWeight;
   Double_t        JHUKD_H_qqZZ_noPDF;
   Double_t        JHU_ME_H;
   Double_t        MCFM_ME_qqZZ;
   Double_t        JHUKD_H_h0M_noPDF;
   Double_t        JHU_ME_h0M;
   Double_t        JHUKD_H_h0P_noPDF;
   Double_t        JHU_ME_h0P;
   Double_t        JHUKD_H_h1M_noPDF;
   Double_t        JHU_ME_h1M;
   Double_t        JHUKD_H_h1P_noPDF;
   Double_t        JHU_ME_h1P;
   Double_t        JHUKD_H_ggh2P_noPDF;
   Double_t        JHU_ME_ggh2P;
   Double_t        JHUKD_H_qqh2P_noPDF;
   Double_t        JHU_ME_qqh2P;
   Double_t        JHUKD_H_h2hP_noPDF;
   Double_t        JHU_ME_h2hP;
   Double_t        JHUKD_H_h2hM_noPDF;
   Double_t        JHU_ME_h2hM;
   Double_t        JHUKD_H_h2bP_noPDF;
   Double_t        JHU_ME_h2bP;
   Double_t        JHUKD_H_h2P_prodInd_noPDF;
   Double_t        JHU_ME_h2P_prodInd;
   Double_t        JHUKD_H_h1P_prodInd_noPDF;
   Double_t        JHU_ME_h1P_prodInd;
   Double_t        JHUKD_H_h1M_prodInd_noPDF;
   Double_t        JHU_ME_h1M_prodInd;
   Double_t        MEKD_noPDF_noFSR;
   Double_t        MEKD_ME_H_noPDF_noFSR;
   Double_t        MEKD_ME_ZZ_noPDF_noFSR;
   Double_t        MEKD_h0M_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h0M_noPDF_noFSR;
   Double_t        MEKD_h0P_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h0P_noPDF_noFSR;
   Double_t        MEKD_h1M_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h1M_noPDF_noFSR;
   Double_t        MEKD_h1P_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h1P_noPDF_noFSR;
   Double_t        MEKD_qqh2P_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_qqh2P_noPDF_noFSR;
   Double_t        MEKD_ggh2P_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_ggh2P_noPDF_noFSR;
   Double_t        MEKD_h2hP_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h2hP_noPDF_noFSR;
   Double_t        MEKD_h2hM_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h2hM_noPDF_noFSR;
   Double_t        MEKD_h2bP_ZZ_noPDF_noFSR;
   Double_t        MEKD_ME_h2bP_noPDF_noFSR;
   Double_t        MEKD_h2P_ZZ_prodInd_noPDF_noFSR;
   Double_t        MEKD_ME_h2P_prodInd_noPDF_noFSR;
   Double_t        MEKD_h1P_ZZ_prodInd_noPDF_noFSR;
   Double_t        MEKD_ME_h1P_prodInd_noPDF_noFSR;
   Double_t        MEKD_h1M_ZZ_prodInd_noPDF_noFSR;
   Double_t        MEKD_ME_h1M_prodInd_noPDF_noFSR;
   Double_t        JHUKD_H_qqZZ_noPDF_noFSR;
   Double_t        JHU_ME_H_noPDF_noFSR;
   Double_t        JHU_ME_ZZ_noPDF_noFSR;
   Double_t        JHUKD_h0M_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_h0M_noPDF_noFSR;
   Double_t        JHUKD_h0P_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_h0P_noPDF_noFSR;
   Double_t        JHUKD_h1M_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_h1M_noPDF_noFSR;
   Double_t        JHUKD_h1P_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_h1P_noPDF_noFSR;
   Double_t        JHUKD_qqh2P_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_qqh2P_noPDF_noFSR;
   Double_t        JHUKD_ggh2P_ZZ_noPDF_noFSR;
   Double_t        JHU_ME_ggh2P_noPDF_noFSR;
   Int_t           GENidL1_S1;
   Int_t           GENidL2_S1;
   Int_t           GENidL3_S1;
   Int_t           GENidL4_S1;
   Double_t        GENEL1_S1;
   Double_t        GENEL2_S1;
   Double_t        GENEL3_S1;
   Double_t        GENEL4_S1;
   Int_t           GENidL1_S3;
   Int_t           GENidL2_S3;
   Int_t           GENidL3_S3;
   Int_t           GENidL4_S3;
   Double_t        GENEL1_S3;
   Double_t        GENEL2_S3;
   Double_t        GENEL3_S3;
   Double_t        GENEL4_S3;
   Double_t        GENEZ1;
   Double_t        GENEZ2;
   Double_t        GENMZ1;
   Double_t        GENMZ2;
   Double_t        GENpTL1_S1;
   Double_t        GENpTL2_S1;
   Double_t        GENpTL3_S1;
   Double_t        GENpTL4_S1;
   Double_t        GENpXL1_S1;
   Double_t        GENpXL2_S1;
   Double_t        GENpXL3_S1;
   Double_t        GENpXL4_S1;
   Double_t        GENpYL1_S1;
   Double_t        GENpYL2_S1;
   Double_t        GENpYL3_S1;
   Double_t        GENpYL4_S1;
   Double_t        GENpZL1_S1;
   Double_t        GENpZL2_S1;
   Double_t        GENpZL3_S1;
   Double_t        GENpZL4_S1;
   Double_t        GENpTL1_S3;
   Double_t        GENpTL2_S3;
   Double_t        GENpTL3_S3;
   Double_t        GENpTL4_S3;
   Double_t        GENpXL1_S3;
   Double_t        GENpXL2_S3;
   Double_t        GENpXL3_S3;
   Double_t        GENpXL4_S3;
   Double_t        GENpYL1_S3;
   Double_t        GENpYL2_S3;
   Double_t        GENpYL3_S3;
   Double_t        GENpYL4_S3;
   Double_t        GENpZL1_S3;
   Double_t        GENpZL2_S3;
   Double_t        GENpZL3_S3;
   Double_t        GENpZL4_S3;
   Double_t        GENpTZ1;
   Double_t        GENpTZ2;
   Double_t        GENpXZ1;
   Double_t        GENpXZ2;
   Double_t        GENpYZ1;
   Double_t        GENpYZ2;
   Double_t        GENpZZ1;
   Double_t        GENpZZ2;
   Int_t           GENchargeL1_S1;
   Int_t           GENchargeL2_S1;
   Int_t           GENchargeL3_S1;
   Int_t           GENchargeL4_S1;
   Double_t        GENetaL1_S1;
   Double_t        GENetaL2_S1;
   Double_t        GENetaL3_S1;
   Double_t        GENetaL4_S1;
   Double_t        GENphiL1_S1;
   Double_t        GENphiL2_S1;
   Double_t        GENphiL3_S1;
   Double_t        GENphiL4_S1;
   Int_t           GENchargeL1_S3;
   Int_t           GENchargeL2_S3;
   Int_t           GENchargeL3_S3;
   Int_t           GENchargeL4_S3;
   Double_t        GENetaL1_S3;
   Double_t        GENetaL2_S3;
   Double_t        GENetaL3_S3;
   Double_t        GENetaL4_S3;
   Double_t        GENphiL1_S3;
   Double_t        GENphiL2_S3;
   Double_t        GENphiL3_S3;
   Double_t        GENphiL4_S3;
   Double_t        GENMH;
   Double_t        GENM4L;
   Double_t        m4l_GENMatched;
   Int_t           idL1_GENMatched;
   Int_t           idL2_GENMatched;
   Int_t           idL3_GENMatched;
   Int_t           idL4_GENMatched;
   Double_t        pTL1_GENMatched;
   Double_t        pTL2_GENMatched;
   Double_t        pTL3_GENMatched;
   Double_t        pTL4_GENMatched;
   Double_t        pXL1_GENMatched;
   Double_t        pXL2_GENMatched;
   Double_t        pXL3_GENMatched;
   Double_t        pXL4_GENMatched;
   Double_t        pYL1_GENMatched;
   Double_t        pYL2_GENMatched;
   Double_t        pYL3_GENMatched;
   Double_t        pYL4_GENMatched;
   Double_t        pZL1_GENMatched;
   Double_t        pZL2_GENMatched;
   Double_t        pZL3_GENMatched;
   Double_t        pZL4_GENMatched;
   Double_t        EL1_GENMatched;
   Double_t        EL2_GENMatched;
   Double_t        EL3_GENMatched;
   Double_t        EL4_GENMatched;
   Int_t           chargeL1_GENMatched;
   Int_t           chargeL2_GENMatched;
   Int_t           chargeL3_GENMatched;
   Int_t           chargeL4_GENMatched;
   Double_t        etaL1_GENMatched;
   Double_t        etaL2_GENMatched;
   Double_t        etaL3_GENMatched;
   Double_t        etaL4_GENMatched;
   Double_t        phiL1_GENMatched;
   Double_t        phiL2_GENMatched;
   Double_t        phiL3_GENMatched;
   Double_t        phiL4_GENMatched;
   Double_t        EZ1_GENMatched;
   Double_t        EZ2_GENMatched;
   Double_t        pTZ1_GENMatched;
   Double_t        pTZ2_GENMatched;
   Double_t        pXZ1_GENMatched;
   Double_t        pXZ2_GENMatched;
   Double_t        pYZ1_GENMatched;
   Double_t        pYZ2_GENMatched;
   Double_t        pZZ1_GENMatched;
   Double_t        pZZ2_GENMatched;
   Bool_t          VBFJet1;
   Double_t        etaVBFJet1;
   Double_t        phiVBFJet1;
   Double_t        pTVBFJet1;
   Double_t        massVBFJet1;
   Bool_t          VBFJet2;
   Double_t        etaVBFJet2;
   Double_t        phiVBFJet2;
   Double_t        pTVBFJet2;
   Double_t        massVBFJet2;
   Double_t        VBFDiJetMass;
   Double_t        VBFDeltaEta;
   Double_t        FisherDiscrim;

   // Set branch addresses.
   passedEvents->SetBranchAddress("Run",&Run);
   passedEvents->SetBranchAddress("Event",&Event);
   passedEvents->SetBranchAddress("LumiSect",&LumiSect);
   passedEvents->SetBranchAddress("EventType",&EventType);
   passedEvents->SetBranchAddress("mass4l",&mass4l);
   passedEvents->SetBranchAddress("ZZMass",&ZZMass);
   passedEvents->SetBranchAddress("mass4lNoFSR",&mass4lNoFSR);
   passedEvents->SetBranchAddress("mass4mu",&mass4mu);
   passedEvents->SetBranchAddress("mass4e",&mass4e);
   passedEvents->SetBranchAddress("mass2e2mu",&mass2e2mu);
   passedEvents->SetBranchAddress("minMass3l",&minMass3l);
   passedEvents->SetBranchAddress("M3l_softestLep",&M3l_softestLep);
   passedEvents->SetBranchAddress("Z4l_maxP",&Z4l_maxP);
   passedEvents->SetBranchAddress("minDeltaR",&minDeltaR);
   passedEvents->SetBranchAddress("Z4l_thetaPhoton",&Z4l_thetaPhoton);
   passedEvents->SetBranchAddress("Z4l_thetaPhoton_deg",&Z4l_thetaPhoton_deg);
   passedEvents->SetBranchAddress("Z4l_thetaPhotonZ",&Z4l_thetaPhotonZ);
   passedEvents->SetBranchAddress("Z4l_thetaPhotonZ_deg",&Z4l_thetaPhotonZ_deg);
   passedEvents->SetBranchAddress("Z4l_theta12",&Z4l_theta12);
   passedEvents->SetBranchAddress("Z4l_theta13",&Z4l_theta13);
   passedEvents->SetBranchAddress("Z4l_theta14",&Z4l_theta14);
   passedEvents->SetBranchAddress("Z4l_theta12_deg",&Z4l_theta12_deg);
   passedEvents->SetBranchAddress("Z4l_theta13_deg",&Z4l_theta13_deg);
   passedEvents->SetBranchAddress("Z4l_theta14_deg",&Z4l_theta14_deg);
   passedEvents->SetBranchAddress("Z4l_minMass2l",&Z4l_minMass2l);
   passedEvents->SetBranchAddress("Z4l_maxMass2l",&Z4l_maxMass2l);
   passedEvents->SetBranchAddress("thetaZ2",&thetaZ2);
   passedEvents->SetBranchAddress("etaZ2",&etaZ2);
   passedEvents->SetBranchAddress("passedFullSelection",&passedFullSelection);
   passedEvents->SetBranchAddress("passedZ4lSelection",&passedZ4lSelection);
   passedEvents->SetBranchAddress("passedQCDcut",&passedQCDcut);
   passedEvents->SetBranchAddress("finalState",&finalState);
   passedEvents->SetBranchAddress("mixedFinalState",&mixedFinalState);
   passedEvents->SetBranchAddress("scaleWeight",&scaleWeight);
   passedEvents->SetBranchAddress("eventWeight",&eventWeight);
   passedEvents->SetBranchAddress("MC_weight",&MC_weight);
   passedEvents->SetBranchAddress("pT4l",&pT4l);
   passedEvents->SetBranchAddress("massZ1",&massZ1);
   passedEvents->SetBranchAddress("massZ2",&massZ2);
   passedEvents->SetBranchAddress("Z1Mass",&Z1Mass);
   passedEvents->SetBranchAddress("Z2Mass",&Z2Mass);
   passedEvents->SetBranchAddress("eta4l",&eta4l);
   passedEvents->SetBranchAddress("phi4l",&phi4l);
   passedEvents->SetBranchAddress("idL1",&idL1);
   passedEvents->SetBranchAddress("idL2",&idL2);
   passedEvents->SetBranchAddress("idL3",&idL3);
   passedEvents->SetBranchAddress("idL4",&idL4);
   passedEvents->SetBranchAddress("missingHitsL1",&missingHitsL1);
   passedEvents->SetBranchAddress("missingHitsL2",&missingHitsL2);
   passedEvents->SetBranchAddress("missingHitsL3",&missingHitsL3);
   passedEvents->SetBranchAddress("missingHitsL4",&missingHitsL4);
   passedEvents->SetBranchAddress("ecalSeedL1",&ecalSeedL1);
   passedEvents->SetBranchAddress("ecalSeedL2",&ecalSeedL2);
   passedEvents->SetBranchAddress("ecalSeedL3",&ecalSeedL3);
   passedEvents->SetBranchAddress("ecalSeedL4",&ecalSeedL4);
   passedEvents->SetBranchAddress("EL1",&EL1);
   passedEvents->SetBranchAddress("EL2",&EL2);
   passedEvents->SetBranchAddress("EL3",&EL3);
   passedEvents->SetBranchAddress("EL4",&EL4);
   passedEvents->SetBranchAddress("EL1FSR",&EL1FSR);
   passedEvents->SetBranchAddress("EL2FSR",&EL2FSR);
   passedEvents->SetBranchAddress("EL3FSR",&EL3FSR);
   passedEvents->SetBranchAddress("EL4FSR",&EL4FSR);
   passedEvents->SetBranchAddress("mvaL1",&mvaL1);
   passedEvents->SetBranchAddress("mvaL2",&mvaL2);
   passedEvents->SetBranchAddress("mvaL3",&mvaL3);
   passedEvents->SetBranchAddress("mvaL4",&mvaL4);
   passedEvents->SetBranchAddress("SipL1",&SipL1);
   passedEvents->SetBranchAddress("SipL2",&SipL2);
   passedEvents->SetBranchAddress("SipL3",&SipL3);
   passedEvents->SetBranchAddress("SipL4",&SipL4);
   passedEvents->SetBranchAddress("IPL1",&IPL1);
   passedEvents->SetBranchAddress("IPL2",&IPL2);
   passedEvents->SetBranchAddress("IPL3",&IPL3);
   passedEvents->SetBranchAddress("IPL4",&IPL4);
   passedEvents->SetBranchAddress("dIPL1",&dIPL1);
   passedEvents->SetBranchAddress("dIPL2",&dIPL2);
   passedEvents->SetBranchAddress("dIPL3",&dIPL3);
   passedEvents->SetBranchAddress("dIPL4",&dIPL4);
   passedEvents->SetBranchAddress("EZ1",&EZ1);
   passedEvents->SetBranchAddress("EZ2",&EZ2);
   passedEvents->SetBranchAddress("pTL1",&pTL1);
   passedEvents->SetBranchAddress("pTL2",&pTL2);
   passedEvents->SetBranchAddress("pTL3",&pTL3);
   passedEvents->SetBranchAddress("pTL4",&pTL4);
   passedEvents->SetBranchAddress("pXL1",&pXL1);
   passedEvents->SetBranchAddress("pXL2",&pXL2);
   passedEvents->SetBranchAddress("pXL3",&pXL3);
   passedEvents->SetBranchAddress("pXL4",&pXL4);
   passedEvents->SetBranchAddress("pYL1",&pYL1);
   passedEvents->SetBranchAddress("pYL2",&pYL2);
   passedEvents->SetBranchAddress("pYL3",&pYL3);
   passedEvents->SetBranchAddress("pYL4",&pYL4);
   passedEvents->SetBranchAddress("pZL1",&pZL1);
   passedEvents->SetBranchAddress("pZL2",&pZL2);
   passedEvents->SetBranchAddress("pZL3",&pZL3);
   passedEvents->SetBranchAddress("pZL4",&pZL4);
   passedEvents->SetBranchAddress("pTL1FSR",&pTL1FSR);
   passedEvents->SetBranchAddress("pTL2FSR",&pTL2FSR);
   passedEvents->SetBranchAddress("pTL3FSR",&pTL3FSR);
   passedEvents->SetBranchAddress("pTL4FSR",&pTL4FSR);
   passedEvents->SetBranchAddress("pXL1FSR",&pXL1FSR);
   passedEvents->SetBranchAddress("pXL2FSR",&pXL2FSR);
   passedEvents->SetBranchAddress("pXL3FSR",&pXL3FSR);
   passedEvents->SetBranchAddress("pXL4FSR",&pXL4FSR);
   passedEvents->SetBranchAddress("pYL1FSR",&pYL1FSR);
   passedEvents->SetBranchAddress("pYL2FSR",&pYL2FSR);
   passedEvents->SetBranchAddress("pYL3FSR",&pYL3FSR);
   passedEvents->SetBranchAddress("pYL4FSR",&pYL4FSR);
   passedEvents->SetBranchAddress("pZL1FSR",&pZL1FSR);
   passedEvents->SetBranchAddress("pZL2FSR",&pZL2FSR);
   passedEvents->SetBranchAddress("pZL3FSR",&pZL3FSR);
   passedEvents->SetBranchAddress("pZL4FSR",&pZL4FSR);
   passedEvents->SetBranchAddress("pTZ1",&pTZ1);
   passedEvents->SetBranchAddress("pTZ2",&pTZ2);
   passedEvents->SetBranchAddress("pXZ1",&pXZ1);
   passedEvents->SetBranchAddress("pXZ2",&pXZ2);
   passedEvents->SetBranchAddress("pYZ1",&pYZ1);
   passedEvents->SetBranchAddress("pYZ2",&pYZ2);
   passedEvents->SetBranchAddress("pZZ1",&pZZ1);
   passedEvents->SetBranchAddress("pZZ2",&pZZ2);
   passedEvents->SetBranchAddress("chargeL1",&chargeL1);
   passedEvents->SetBranchAddress("chargeL2",&chargeL2);
   passedEvents->SetBranchAddress("chargeL3",&chargeL3);
   passedEvents->SetBranchAddress("chargeL4",&chargeL4);
   passedEvents->SetBranchAddress("etaL1",&etaL1);
   passedEvents->SetBranchAddress("etaL2",&etaL2);
   passedEvents->SetBranchAddress("etaL3",&etaL3);
   passedEvents->SetBranchAddress("etaL4",&etaL4);
   passedEvents->SetBranchAddress("phiL1",&phiL1);
   passedEvents->SetBranchAddress("phiL2",&phiL2);
   passedEvents->SetBranchAddress("phiL3",&phiL3);
   passedEvents->SetBranchAddress("phiL4",&phiL4);
   passedEvents->SetBranchAddress("isoTrackL1",&isoTrackL1);
   passedEvents->SetBranchAddress("isoTrackL2",&isoTrackL2);
   passedEvents->SetBranchAddress("isoTrackL3",&isoTrackL3);
   passedEvents->SetBranchAddress("isoTrackL4",&isoTrackL4);
   passedEvents->SetBranchAddress("isoEcalL1",&isoEcalL1);
   passedEvents->SetBranchAddress("isoEcalL2",&isoEcalL2);
   passedEvents->SetBranchAddress("isoEcalL3",&isoEcalL3);
   passedEvents->SetBranchAddress("isoEcalL4",&isoEcalL4);
   passedEvents->SetBranchAddress("isoHcalL1",&isoHcalL1);
   passedEvents->SetBranchAddress("isoHcalL2",&isoHcalL2);
   passedEvents->SetBranchAddress("isoHcalL3",&isoHcalL3);
   passedEvents->SetBranchAddress("isoHcalL4",&isoHcalL4);
   passedEvents->SetBranchAddress("isoNHL1",&isoNHL1);
   passedEvents->SetBranchAddress("isoNHL2",&isoNHL2);
   passedEvents->SetBranchAddress("isoNHL3",&isoNHL3);
   passedEvents->SetBranchAddress("isoNHL4",&isoNHL4);
   passedEvents->SetBranchAddress("isoCHL1",&isoCHL1);
   passedEvents->SetBranchAddress("isoCHL2",&isoCHL2);
   passedEvents->SetBranchAddress("isoCHL3",&isoCHL3);
   passedEvents->SetBranchAddress("isoCHL4",&isoCHL4);
   passedEvents->SetBranchAddress("isoPhotL1",&isoPhotL1);
   passedEvents->SetBranchAddress("isoPhotL2",&isoPhotL2);
   passedEvents->SetBranchAddress("isoPhotL3",&isoPhotL3);
   passedEvents->SetBranchAddress("isoPhotL4",&isoPhotL4);
   passedEvents->SetBranchAddress("RelIsoL1",&RelIsoL1);
   passedEvents->SetBranchAddress("RelIsoL2",&RelIsoL2);
   passedEvents->SetBranchAddress("RelIsoL3",&RelIsoL3);
   passedEvents->SetBranchAddress("RelIsoL4",&RelIsoL4);
   passedEvents->SetBranchAddress("RelIsoUCL1",&RelIsoUCL1);
   passedEvents->SetBranchAddress("RelIsoUCL2",&RelIsoUCL2);
   passedEvents->SetBranchAddress("RelIsoUCL3",&RelIsoUCL3);
   passedEvents->SetBranchAddress("RelIsoUCL4",&RelIsoUCL4);
   passedEvents->SetBranchAddress("muRho",&muRho);
   passedEvents->SetBranchAddress("elRho",&elRho);
   passedEvents->SetBranchAddress("worstIso",&worstIso);
   passedEvents->SetBranchAddress("worstSIP",&worstSIP);
   passedEvents->SetBranchAddress("helcosthetaZ1",&helcosthetaZ1);
   passedEvents->SetBranchAddress("helcosthetaZ2",&helcosthetaZ2);
   passedEvents->SetBranchAddress("helphi",&helphi);
   passedEvents->SetBranchAddress("costhetastar",&costhetastar);
   passedEvents->SetBranchAddress("phistarZ1",&phistarZ1);
   passedEvents->SetBranchAddress("nJets",&nJets);
   passedEvents->SetBranchAddress("nVtx",&nVtx);
   passedEvents->SetBranchAddress("nPhotons",&nPhotons);
   passedEvents->SetBranchAddress("metVal",&metVal);
   passedEvents->SetBranchAddress("extraLep_id",extraLep_id);
   passedEvents->SetBranchAddress("extraLep_pT",extraLep_pT);
   passedEvents->SetBranchAddress("extraLep_pX",extraLep_pX);
   passedEvents->SetBranchAddress("extraLep_pY",extraLep_pY);
   passedEvents->SetBranchAddress("extraLep_pZ",extraLep_pZ);
   passedEvents->SetBranchAddress("extraLep_e",extraLep_e);
   passedEvents->SetBranchAddress("extraLep_iso",extraLep_iso);
   passedEvents->SetBranchAddress("extraLep_chIso",extraLep_chIso);
   passedEvents->SetBranchAddress("extraLep_nhIso",extraLep_nhIso);
   passedEvents->SetBranchAddress("extraLep_phIso",extraLep_phIso);
   passedEvents->SetBranchAddress("extraLep_eta",extraLep_eta);
   passedEvents->SetBranchAddress("extraLep_phi",extraLep_phi);
   passedEvents->SetBranchAddress("extraLep_sip",extraLep_sip);
   passedEvents->SetBranchAddress("massErrorUF",&massErrorUF);
   passedEvents->SetBranchAddress("massErrorUFCorr",&massErrorUFCorr);
   passedEvents->SetBranchAddress("massErrorUCSD",&massErrorUCSD);
   passedEvents->SetBranchAddress("massErrorUCSDCorr",&massErrorUCSDCorr);
   passedEvents->SetBranchAddress("FSR_Z1",&FSR_Z1);
   passedEvents->SetBranchAddress("FSR_Z2",&FSR_Z2);
   passedEvents->SetBranchAddress("FSRPhot1_Pt",&FSRPhot1_Pt);
   passedEvents->SetBranchAddress("FSRPhot2_Pt",&FSRPhot2_Pt);
   passedEvents->SetBranchAddress("FSRPhot1_eta",&FSRPhot1_eta);
   passedEvents->SetBranchAddress("FSRPhot2_eta",&FSRPhot2_eta);
   passedEvents->SetBranchAddress("FSRPhot1_phi",&FSRPhot1_phi);
   passedEvents->SetBranchAddress("FSRPhot2_phi",&FSRPhot2_phi);
   passedEvents->SetBranchAddress("FSRPhot1_Px",&FSRPhot1_Px);
   passedEvents->SetBranchAddress("FSRPhot2_Px",&FSRPhot2_Px);
   passedEvents->SetBranchAddress("FSRPhot1_Py",&FSRPhot1_Py);
   passedEvents->SetBranchAddress("FSRPhot2_Py",&FSRPhot2_Py);
   passedEvents->SetBranchAddress("FSRPhot1_Pz",&FSRPhot1_Pz);
   passedEvents->SetBranchAddress("FSRPhot2_Pz",&FSRPhot2_Pz);
   passedEvents->SetBranchAddress("FSRPhot1_E",&FSRPhot1_E);
   passedEvents->SetBranchAddress("FSRPhot2_E",&FSRPhot2_E);
   passedEvents->SetBranchAddress("pdfSigM4l",&pdfSigM4l);
   passedEvents->SetBranchAddress("pdfSigM4l_noFSR",&pdfSigM4l_noFSR);
   passedEvents->SetBranchAddress("pdfBkgM4l",&pdfBkgM4l);
   passedEvents->SetBranchAddress("pdfBkgM4l_noFSR",&pdfBkgM4l_noFSR);
   passedEvents->SetBranchAddress("pdfSigM4l_ScaleUp",&pdfSigM4l_ScaleUp);
   passedEvents->SetBranchAddress("pdfSigM4l_ScaleUp_noFSR",&pdfSigM4l_ScaleUp_noFSR);
   passedEvents->SetBranchAddress("pdfBkgM4l_ScaleUp",&pdfBkgM4l_ScaleUp);
   passedEvents->SetBranchAddress("pdfBkgM4l_ScaleUp_noFSR",&pdfBkgM4l_ScaleUp_noFSR);
   passedEvents->SetBranchAddress("pdfSigM4l_ScaleDown",&pdfSigM4l_ScaleDown);
   passedEvents->SetBranchAddress("pdfSigM4l_ScaleDown_noFSR",&pdfSigM4l_ScaleDown_noFSR);
   passedEvents->SetBranchAddress("pdfBkgM4l_ScaleDown",&pdfBkgM4l_ScaleDown);
   passedEvents->SetBranchAddress("pdfBkgM4l_ScaleDown_noFSR",&pdfBkgM4l_ScaleDown_noFSR);
   passedEvents->SetBranchAddress("pdfSigM4l_ResUp",&pdfSigM4l_ResUp);
   passedEvents->SetBranchAddress("pdfSigM4l_ResUp_noFSR",&pdfSigM4l_ResUp_noFSR);
   passedEvents->SetBranchAddress("pdfBkgM4l_ResUp",&pdfBkgM4l_ResUp);
   passedEvents->SetBranchAddress("pdfBkgM4l_ResUp_noFSR",&pdfBkgM4l_ResUp_noFSR);
   passedEvents->SetBranchAddress("pdfSigM4l_ResDown",&pdfSigM4l_ResDown);
   passedEvents->SetBranchAddress("pdfSigM4l_ResDown_noFSR",&pdfSigM4l_ResDown_noFSR);
   passedEvents->SetBranchAddress("pdfBkgM4l_ResDown",&pdfBkgM4l_ResDown);
   passedEvents->SetBranchAddress("pdfBkgM4l_ResDown_noFSR",&pdfBkgM4l_ResDown_noFSR);
   passedEvents->SetBranchAddress("melaLD",&melaLD);
   passedEvents->SetBranchAddress("mela_Sig",&mela_Sig);
   passedEvents->SetBranchAddress("mela_Bkg",&mela_Bkg);
   passedEvents->SetBranchAddress("pseudoMelaLD",&pseudoMelaLD);
   passedEvents->SetBranchAddress("pseudoMela_SM",&pseudoMela_SM);
   passedEvents->SetBranchAddress("pseudoMela_PS",&pseudoMela_PS);
   passedEvents->SetBranchAddress("spin1EvMelaLD",&spin1EvMelaLD);
   passedEvents->SetBranchAddress("spin1EvMela_SM",&spin1EvMela_SM);
   passedEvents->SetBranchAddress("spin1EvMela_S1E",&spin1EvMela_S1E);
   passedEvents->SetBranchAddress("spin1OddMelaLD",&spin1OddMelaLD);
   passedEvents->SetBranchAddress("spin1OddMela_SM",&spin1OddMela_SM);
   passedEvents->SetBranchAddress("spin1OddMela_S1O",&spin1OddMela_S1O);
   passedEvents->SetBranchAddress("spin2MelaLD",&spin2MelaLD);
   passedEvents->SetBranchAddress("spin2Mela_SM",&spin2Mela_SM);
   passedEvents->SetBranchAddress("spin2Mela_S2",&spin2Mela_S2);
   passedEvents->SetBranchAddress("MEKD_wPDF",&MEKD_wPDF);
   passedEvents->SetBranchAddress("MEKD_ME_H_wPDF",&MEKD_ME_H_wPDF);
   passedEvents->SetBranchAddress("MEKD_ME_ZZ_wPDF",&MEKD_ME_ZZ_wPDF);
   passedEvents->SetBranchAddress("MEKD_noPDF",&MEKD_noPDF);
   passedEvents->SetBranchAddress("MEKD_ME_H_noPDF",&MEKD_ME_H_noPDF);
   passedEvents->SetBranchAddress("MEKD_ME_ZZ_noPDF",&MEKD_ME_ZZ_noPDF);
   passedEvents->SetBranchAddress("MEKD_wPDF_noFSR",&MEKD_wPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_H_wPDF_noFSR",&MEKD_ME_H_wPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_ZZ_wPDF_noFSR",&MEKD_ME_ZZ_wPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_noPDF_noFSR",&MEKD_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_H_noPDF_noFSR",&MEKD_ME_H_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_ZZ_noPDF_noFSR",&MEKD_ME_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("interferenceWeight",&interferenceWeight);
   passedEvents->SetBranchAddress("JHUKD_H_qqZZ_noPDF",&JHUKD_H_qqZZ_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_H",&JHU_ME_H);
   passedEvents->SetBranchAddress("MCFM_ME_qqZZ",&MCFM_ME_qqZZ);
   passedEvents->SetBranchAddress("JHUKD_H_h0M_noPDF",&JHUKD_H_h0M_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h0M",&JHU_ME_h0M);
   passedEvents->SetBranchAddress("JHUKD_H_h0P_noPDF",&JHUKD_H_h0P_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h0P",&JHU_ME_h0P);
   passedEvents->SetBranchAddress("JHUKD_H_h1M_noPDF",&JHUKD_H_h1M_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h1M",&JHU_ME_h1M);
   passedEvents->SetBranchAddress("JHUKD_H_h1P_noPDF",&JHUKD_H_h1P_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h1P",&JHU_ME_h1P);
   passedEvents->SetBranchAddress("JHUKD_H_ggh2P_noPDF",&JHUKD_H_ggh2P_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_ggh2P",&JHU_ME_ggh2P);
   passedEvents->SetBranchAddress("JHUKD_H_qqh2P_noPDF",&JHUKD_H_qqh2P_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_qqh2P",&JHU_ME_qqh2P);
   passedEvents->SetBranchAddress("JHUKD_H_h2hP_noPDF",&JHUKD_H_h2hP_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h2hP",&JHU_ME_h2hP);
   passedEvents->SetBranchAddress("JHUKD_H_h2hM_noPDF",&JHUKD_H_h2hM_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h2hM",&JHU_ME_h2hM);
   passedEvents->SetBranchAddress("JHUKD_H_h2bP_noPDF",&JHUKD_H_h2bP_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h2bP",&JHU_ME_h2bP);
   passedEvents->SetBranchAddress("JHUKD_H_h2P_prodInd_noPDF",&JHUKD_H_h2P_prodInd_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h2P_prodInd",&JHU_ME_h2P_prodInd);
   passedEvents->SetBranchAddress("JHUKD_H_h1P_prodInd_noPDF",&JHUKD_H_h1P_prodInd_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h1P_prodInd",&JHU_ME_h1P_prodInd);
   passedEvents->SetBranchAddress("JHUKD_H_h1M_prodInd_noPDF",&JHUKD_H_h1M_prodInd_noPDF);
   passedEvents->SetBranchAddress("JHU_ME_h1M_prodInd",&JHU_ME_h1M_prodInd);
   passedEvents->SetBranchAddress("MEKD_noPDF_noFSR",&MEKD_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_H_noPDF_noFSR",&MEKD_ME_H_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_ZZ_noPDF_noFSR",&MEKD_ME_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h0M_ZZ_noPDF_noFSR",&MEKD_h0M_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h0M_noPDF_noFSR",&MEKD_ME_h0M_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h0P_ZZ_noPDF_noFSR",&MEKD_h0P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h0P_noPDF_noFSR",&MEKD_ME_h0P_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h1M_ZZ_noPDF_noFSR",&MEKD_h1M_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h1M_noPDF_noFSR",&MEKD_ME_h1M_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h1P_ZZ_noPDF_noFSR",&MEKD_h1P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h1P_noPDF_noFSR",&MEKD_ME_h1P_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_qqh2P_ZZ_noPDF_noFSR",&MEKD_qqh2P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_qqh2P_noPDF_noFSR",&MEKD_ME_qqh2P_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ggh2P_ZZ_noPDF_noFSR",&MEKD_ggh2P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_ggh2P_noPDF_noFSR",&MEKD_ME_ggh2P_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h2hP_ZZ_noPDF_noFSR",&MEKD_h2hP_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h2hP_noPDF_noFSR",&MEKD_ME_h2hP_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h2hM_ZZ_noPDF_noFSR",&MEKD_h2hM_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h2hM_noPDF_noFSR",&MEKD_ME_h2hM_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h2bP_ZZ_noPDF_noFSR",&MEKD_h2bP_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h2bP_noPDF_noFSR",&MEKD_ME_h2bP_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h2P_ZZ_prodInd_noPDF_noFSR",&MEKD_h2P_ZZ_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h2P_prodInd_noPDF_noFSR",&MEKD_ME_h2P_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h1P_ZZ_prodInd_noPDF_noFSR",&MEKD_h1P_ZZ_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h1P_prodInd_noPDF_noFSR",&MEKD_ME_h1P_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_h1M_ZZ_prodInd_noPDF_noFSR",&MEKD_h1M_ZZ_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("MEKD_ME_h1M_prodInd_noPDF_noFSR",&MEKD_ME_h1M_prodInd_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_H_qqZZ_noPDF_noFSR",&JHUKD_H_qqZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_H_noPDF_noFSR",&JHU_ME_H_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_ZZ_noPDF_noFSR",&JHU_ME_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_h0M_ZZ_noPDF_noFSR",&JHUKD_h0M_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_h0M_noPDF_noFSR",&JHU_ME_h0M_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_h0P_ZZ_noPDF_noFSR",&JHUKD_h0P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_h0P_noPDF_noFSR",&JHU_ME_h0P_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_h1M_ZZ_noPDF_noFSR",&JHUKD_h1M_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_h1M_noPDF_noFSR",&JHU_ME_h1M_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_h1P_ZZ_noPDF_noFSR",&JHUKD_h1P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_h1P_noPDF_noFSR",&JHU_ME_h1P_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_qqh2P_ZZ_noPDF_noFSR",&JHUKD_qqh2P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_qqh2P_noPDF_noFSR",&JHU_ME_qqh2P_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHUKD_ggh2P_ZZ_noPDF_noFSR",&JHUKD_ggh2P_ZZ_noPDF_noFSR);
   passedEvents->SetBranchAddress("JHU_ME_ggh2P_noPDF_noFSR",&JHU_ME_ggh2P_noPDF_noFSR);
   passedEvents->SetBranchAddress("GENidL1_S1",&GENidL1_S1);
   passedEvents->SetBranchAddress("GENidL2_S1",&GENidL2_S1);
   passedEvents->SetBranchAddress("GENidL3_S1",&GENidL3_S1);
   passedEvents->SetBranchAddress("GENidL4_S1",&GENidL4_S1);
   passedEvents->SetBranchAddress("GENEL1_S1",&GENEL1_S1);
   passedEvents->SetBranchAddress("GENEL2_S1",&GENEL2_S1);
   passedEvents->SetBranchAddress("GENEL3_S1",&GENEL3_S1);
   passedEvents->SetBranchAddress("GENEL4_S1",&GENEL4_S1);
   passedEvents->SetBranchAddress("GENidL1_S3",&GENidL1_S3);
   passedEvents->SetBranchAddress("GENidL2_S3",&GENidL2_S3);
   passedEvents->SetBranchAddress("GENidL3_S3",&GENidL3_S3);
   passedEvents->SetBranchAddress("GENidL4_S3",&GENidL4_S3);
   passedEvents->SetBranchAddress("GENEL1_S3",&GENEL1_S3);
   passedEvents->SetBranchAddress("GENEL2_S3",&GENEL2_S3);
   passedEvents->SetBranchAddress("GENEL3_S3",&GENEL3_S3);
   passedEvents->SetBranchAddress("GENEL4_S3",&GENEL4_S3);
   passedEvents->SetBranchAddress("GENEZ1",&GENEZ1);
   passedEvents->SetBranchAddress("GENEZ2",&GENEZ2);
   passedEvents->SetBranchAddress("GENMZ1",&GENMZ1);
   passedEvents->SetBranchAddress("GENMZ2",&GENMZ2);
   passedEvents->SetBranchAddress("GENpTL1_S1",&GENpTL1_S1);
   passedEvents->SetBranchAddress("GENpTL2_S1",&GENpTL2_S1);
   passedEvents->SetBranchAddress("GENpTL3_S1",&GENpTL3_S1);
   passedEvents->SetBranchAddress("GENpTL4_S1",&GENpTL4_S1);
   passedEvents->SetBranchAddress("GENpXL1_S1",&GENpXL1_S1);
   passedEvents->SetBranchAddress("GENpXL2_S1",&GENpXL2_S1);
   passedEvents->SetBranchAddress("GENpXL3_S1",&GENpXL3_S1);
   passedEvents->SetBranchAddress("GENpXL4_S1",&GENpXL4_S1);
   passedEvents->SetBranchAddress("GENpYL1_S1",&GENpYL1_S1);
   passedEvents->SetBranchAddress("GENpYL2_S1",&GENpYL2_S1);
   passedEvents->SetBranchAddress("GENpYL3_S1",&GENpYL3_S1);
   passedEvents->SetBranchAddress("GENpYL4_S1",&GENpYL4_S1);
   passedEvents->SetBranchAddress("GENpZL1_S1",&GENpZL1_S1);
   passedEvents->SetBranchAddress("GENpZL2_S1",&GENpZL2_S1);
   passedEvents->SetBranchAddress("GENpZL3_S1",&GENpZL3_S1);
   passedEvents->SetBranchAddress("GENpZL4_S1",&GENpZL4_S1);
   passedEvents->SetBranchAddress("GENpTL1_S3",&GENpTL1_S3);
   passedEvents->SetBranchAddress("GENpTL2_S3",&GENpTL2_S3);
   passedEvents->SetBranchAddress("GENpTL3_S3",&GENpTL3_S3);
   passedEvents->SetBranchAddress("GENpTL4_S3",&GENpTL4_S3);
   passedEvents->SetBranchAddress("GENpXL1_S3",&GENpXL1_S3);
   passedEvents->SetBranchAddress("GENpXL2_S3",&GENpXL2_S3);
   passedEvents->SetBranchAddress("GENpXL3_S3",&GENpXL3_S3);
   passedEvents->SetBranchAddress("GENpXL4_S3",&GENpXL4_S3);
   passedEvents->SetBranchAddress("GENpYL1_S3",&GENpYL1_S3);
   passedEvents->SetBranchAddress("GENpYL2_S3",&GENpYL2_S3);
   passedEvents->SetBranchAddress("GENpYL3_S3",&GENpYL3_S3);
   passedEvents->SetBranchAddress("GENpYL4_S3",&GENpYL4_S3);
   passedEvents->SetBranchAddress("GENpZL1_S3",&GENpZL1_S3);
   passedEvents->SetBranchAddress("GENpZL2_S3",&GENpZL2_S3);
   passedEvents->SetBranchAddress("GENpZL3_S3",&GENpZL3_S3);
   passedEvents->SetBranchAddress("GENpZL4_S3",&GENpZL4_S3);
   passedEvents->SetBranchAddress("GENpTZ1",&GENpTZ1);
   passedEvents->SetBranchAddress("GENpTZ2",&GENpTZ2);
   passedEvents->SetBranchAddress("GENpXZ1",&GENpXZ1);
   passedEvents->SetBranchAddress("GENpXZ2",&GENpXZ2);
   passedEvents->SetBranchAddress("GENpYZ1",&GENpYZ1);
   passedEvents->SetBranchAddress("GENpYZ2",&GENpYZ2);
   passedEvents->SetBranchAddress("GENpZZ1",&GENpZZ1);
   passedEvents->SetBranchAddress("GENpZZ2",&GENpZZ2);
   passedEvents->SetBranchAddress("GENchargeL1_S1",&GENchargeL1_S1);
   passedEvents->SetBranchAddress("GENchargeL2_S1",&GENchargeL2_S1);
   passedEvents->SetBranchAddress("GENchargeL3_S1",&GENchargeL3_S1);
   passedEvents->SetBranchAddress("GENchargeL4_S1",&GENchargeL4_S1);
   passedEvents->SetBranchAddress("GENetaL1_S1",&GENetaL1_S1);
   passedEvents->SetBranchAddress("GENetaL2_S1",&GENetaL2_S1);
   passedEvents->SetBranchAddress("GENetaL3_S1",&GENetaL3_S1);
   passedEvents->SetBranchAddress("GENetaL4_S1",&GENetaL4_S1);
   passedEvents->SetBranchAddress("GENphiL1_S1",&GENphiL1_S1);
   passedEvents->SetBranchAddress("GENphiL2_S1",&GENphiL2_S1);
   passedEvents->SetBranchAddress("GENphiL3_S1",&GENphiL3_S1);
   passedEvents->SetBranchAddress("GENphiL4_S1",&GENphiL4_S1);
   passedEvents->SetBranchAddress("GENchargeL1_S3",&GENchargeL1_S3);
   passedEvents->SetBranchAddress("GENchargeL2_S3",&GENchargeL2_S3);
   passedEvents->SetBranchAddress("GENchargeL3_S3",&GENchargeL3_S3);
   passedEvents->SetBranchAddress("GENchargeL4_S3",&GENchargeL4_S3);
   passedEvents->SetBranchAddress("GENetaL1_S3",&GENetaL1_S3);
   passedEvents->SetBranchAddress("GENetaL2_S3",&GENetaL2_S3);
   passedEvents->SetBranchAddress("GENetaL3_S3",&GENetaL3_S3);
   passedEvents->SetBranchAddress("GENetaL4_S3",&GENetaL4_S3);
   passedEvents->SetBranchAddress("GENphiL1_S3",&GENphiL1_S3);
   passedEvents->SetBranchAddress("GENphiL2_S3",&GENphiL2_S3);
   passedEvents->SetBranchAddress("GENphiL3_S3",&GENphiL3_S3);
   passedEvents->SetBranchAddress("GENphiL4_S3",&GENphiL4_S3);
   passedEvents->SetBranchAddress("GENMH",&GENMH);
   passedEvents->SetBranchAddress("GENM4L",&GENM4L);
   passedEvents->SetBranchAddress("m4l_GENMatched",&m4l_GENMatched);
   passedEvents->SetBranchAddress("idL1_GENMatched",&idL1_GENMatched);
   passedEvents->SetBranchAddress("idL2_GENMatched",&idL2_GENMatched);
   passedEvents->SetBranchAddress("idL3_GENMatched",&idL3_GENMatched);
   passedEvents->SetBranchAddress("idL4_GENMatched",&idL4_GENMatched);
   passedEvents->SetBranchAddress("pTL1_GENMatched",&pTL1_GENMatched);
   passedEvents->SetBranchAddress("pTL2_GENMatched",&pTL2_GENMatched);
   passedEvents->SetBranchAddress("pTL3_GENMatched",&pTL3_GENMatched);
   passedEvents->SetBranchAddress("pTL4_GENMatched",&pTL4_GENMatched);
   passedEvents->SetBranchAddress("pXL1_GENMatched",&pXL1_GENMatched);
   passedEvents->SetBranchAddress("pXL2_GENMatched",&pXL2_GENMatched);
   passedEvents->SetBranchAddress("pXL3_GENMatched",&pXL3_GENMatched);
   passedEvents->SetBranchAddress("pXL4_GENMatched",&pXL4_GENMatched);
   passedEvents->SetBranchAddress("pYL1_GENMatched",&pYL1_GENMatched);
   passedEvents->SetBranchAddress("pYL2_GENMatched",&pYL2_GENMatched);
   passedEvents->SetBranchAddress("pYL3_GENMatched",&pYL3_GENMatched);
   passedEvents->SetBranchAddress("pYL4_GENMatched",&pYL4_GENMatched);
   passedEvents->SetBranchAddress("pZL1_GENMatched",&pZL1_GENMatched);
   passedEvents->SetBranchAddress("pZL2_GENMatched",&pZL2_GENMatched);
   passedEvents->SetBranchAddress("pZL3_GENMatched",&pZL3_GENMatched);
   passedEvents->SetBranchAddress("pZL4_GENMatched",&pZL4_GENMatched);
   passedEvents->SetBranchAddress("EL1_GENMatched",&EL1_GENMatched);
   passedEvents->SetBranchAddress("EL2_GENMatched",&EL2_GENMatched);
   passedEvents->SetBranchAddress("EL3_GENMatched",&EL3_GENMatched);
   passedEvents->SetBranchAddress("EL4_GENMatched",&EL4_GENMatched);
   passedEvents->SetBranchAddress("chargeL1_GENMatched",&chargeL1_GENMatched);
   passedEvents->SetBranchAddress("chargeL2_GENMatched",&chargeL2_GENMatched);
   passedEvents->SetBranchAddress("chargeL3_GENMatched",&chargeL3_GENMatched);
   passedEvents->SetBranchAddress("chargeL4_GENMatched",&chargeL4_GENMatched);
   passedEvents->SetBranchAddress("etaL1_GENMatched",&etaL1_GENMatched);
   passedEvents->SetBranchAddress("etaL2_GENMatched",&etaL2_GENMatched);
   passedEvents->SetBranchAddress("etaL3_GENMatched",&etaL3_GENMatched);
   passedEvents->SetBranchAddress("etaL4_GENMatched",&etaL4_GENMatched);
   passedEvents->SetBranchAddress("phiL1_GENMatched",&phiL1_GENMatched);
   passedEvents->SetBranchAddress("phiL2_GENMatched",&phiL2_GENMatched);
   passedEvents->SetBranchAddress("phiL3_GENMatched",&phiL3_GENMatched);
   passedEvents->SetBranchAddress("phiL4_GENMatched",&phiL4_GENMatched);
   passedEvents->SetBranchAddress("EZ1_GENMatched",&EZ1_GENMatched);
   passedEvents->SetBranchAddress("EZ2_GENMatched",&EZ2_GENMatched);
   passedEvents->SetBranchAddress("pTZ1_GENMatched",&pTZ1_GENMatched);
   passedEvents->SetBranchAddress("pTZ2_GENMatched",&pTZ2_GENMatched);
   passedEvents->SetBranchAddress("pXZ1_GENMatched",&pXZ1_GENMatched);
   passedEvents->SetBranchAddress("pXZ2_GENMatched",&pXZ2_GENMatched);
   passedEvents->SetBranchAddress("pYZ1_GENMatched",&pYZ1_GENMatched);
   passedEvents->SetBranchAddress("pYZ2_GENMatched",&pYZ2_GENMatched);
   passedEvents->SetBranchAddress("pZZ1_GENMatched",&pZZ1_GENMatched);
   passedEvents->SetBranchAddress("pZZ2_GENMatched",&pZZ2_GENMatched);
   passedEvents->SetBranchAddress("VBFJet1",&VBFJet1);
   passedEvents->SetBranchAddress("etaVBFJet1",&etaVBFJet1);
   passedEvents->SetBranchAddress("phiVBFJet1",&phiVBFJet1);
   passedEvents->SetBranchAddress("pTVBFJet1",&pTVBFJet1);
   passedEvents->SetBranchAddress("massVBFJet1",&massVBFJet1);
   passedEvents->SetBranchAddress("VBFJet2",&VBFJet2);
   passedEvents->SetBranchAddress("etaVBFJet2",&etaVBFJet2);
   passedEvents->SetBranchAddress("phiVBFJet2",&phiVBFJet2);
   passedEvents->SetBranchAddress("pTVBFJet2",&pTVBFJet2);
   passedEvents->SetBranchAddress("massVBFJet2",&massVBFJet2);
   passedEvents->SetBranchAddress("VBFDiJetMass",&VBFDiJetMass);
   passedEvents->SetBranchAddress("VBFDeltaEta",&VBFDeltaEta);
   passedEvents->SetBranchAddress("FisherDiscrim",&FisherDiscrim);


   Long64_t nentries = passedEvents->GetEntries();

   Long64_t nbytes = 0;
   for (Long64_t i=0; i<nentries;i++) {
      nbytes += passedEvents->GetEntry(i);
      ULong64_t run0=Run;
      ULong64_t event0=Event;
      for (Long64_t j=i+1; j<nentries;j++) {
        passedEvents->GetEntry(j);
        if (run0==Run &&event0==Event) {
          std::cout << "Duplicated Run: " << run0 << " Event: " << event0 << std::endl;
        }
      }
   }
}
